# Generated by Django 4.1.6 on 2023-02-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='happy_clients',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='hard_worker',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='support',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='tie_ups',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
