# Generated by Django 4.1.6 on 2023-02-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contacts_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
