# Generated by Django 4.1.6 on 2023-02-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testimonials_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer Not to Say')], max_length=10)),
                ('room', models.CharField(choices=[('S', 'Single'), ('D', 'Double'), ('T', 'Triple')], max_length=10)),
                ('college', models.CharField(max_length=100)),
                ('taxi_service', models.BooleanField(default=False)),
                ('hotel_service', models.BooleanField(default=False)),
            ],
        ),
    ]
