# Generated by Django 4.1.6 on 2023-02-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='hotel_service',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='room',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='taxi_service',
            field=models.CharField(max_length=10),
        ),
    ]
