# Generated by Django 4.1.6 on 2023-02-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_register_gender_alter_register_hotel_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='hotel_service',
            field=models.CharField(blank=True, default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='taxi_service',
            field=models.CharField(blank=True, default='No', max_length=10),
        ),
    ]
