# Generated by Django 4.1.6 on 2023-02-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_register_checked_register_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
