# Generated by Django 4.1.6 on 2023-02-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contacts_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='register',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='register',
            name='updated_at',
        ),
    ]
