# Generated by Django 4.1.6 on 2023-02-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_register_checked_remove_register_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='checked',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='No', max_length=5),
        ),
    ]
