# Generated by Django 4.1.6 on 2023-02-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_register_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='checked',
        ),
    ]
