# Generated by Django 4.1.6 on 2023-02-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_register_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='checked',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=5),
        ),
    ]
