# Generated by Django 4.1.6 on 2023-02-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_register_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
